version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: fisioku-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fisioku
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - fisioku-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fisioku-db-data:
    driver: local
